---
- name: Clone project
  git: repo={{ backend.repo }} dest={{ backend.path }} version={{ general.branch }} accept_hostkey=yes

- name: Download dependencies
  npm: path={{ backend.path }}

- name: Copy nginx config file
  template: src=etc/nginx/conf.d/subconf dest=/etc/nginx/conf.d/backend.subconf owner=root group=root
  notify:
  - restart-nginx

- name: Copy supervisor config file
  template: src=etc/supervisor/conf.d/conf dest=/etc/supervisor/conf.d/backend.conf owner=root group=root
  notify:
  - restart-supervisor

- name: Ensure backend is present in supervisorctl
  supervisorctl: name=backend state=present
  notify:
  - start-backend